"""empty message

Revision ID: 7fb12eb0f965
Revises: 8a02b22b3f4a
Create Date: 2024-12-21 22:57:17.456852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb12eb0f965'
down_revision = '8a02b22b3f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessee', schema=None) as batch_op:
        batch_op.alter_column('mobile_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessee', schema=None) as batch_op:
        batch_op.alter_column('mobile_number',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
