"""empty message

Revision ID: fb3ad9c0933d
Revises: 4fe2c88d1065
Create Date: 2024-12-19 12:19:00.630965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3ad9c0933d'
down_revision = '4fe2c88d1065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lessee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lessee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
